# Generated by Django 5.2.8 on 2025-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
